test change

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -40,7 +40,49 @@ jobs:
         chmod +x container-structure-test-linux-amd64
         sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
         make test
-        
+  scan:
+    name: Scan for CVEs
+    runs-on: ubuntu-latest
+    if: always()
+    needs: docker-login
+    steps:
+    - name: Check out working repository
+      uses: actions/checkout@v2
+
+    - name: Build Image
+      run: make image
+
+    - name: Scan image
+      id: scan
+      uses: anchore/scan-action@v3
+      with:
+        image: "pegasystems/pega-ready:latest"
+        fail-build: true
+        severity-cutoff: "high"
+        acs-report-enable: true
+
+    - name: Log Scan Results
+      if: always()
+      run: |
+        echo "Failures:"
+        cat ${{ steps.scan.outputs.sarif }} | jq '.runs[0].tool.driver.rules[].shortDescription.text' | grep -i "critical" || true
+        cat ${{ steps.scan.outputs.sarif }} | jq '.runs[0].tool.driver.rules[].shortDescription.text' | grep -i "high" || true
+        echo "Warnings:"
+        cat ${{ steps.scan.outputs.sarif }} | jq '.runs[0].tool.driver.rules[].shortDescription.text' | grep -i "medium" || true
+        cat ${{ steps.scan.outputs.sarif }} | jq '.runs[0].tool.driver.rules[].shortDescription.text' | grep -i "low" || true
+        cat ${{ steps.scan.outputs.sarif }} | jq '.runs[0].tool.driver.rules[].shortDescription.text' | grep -iv "critical\|high\|medium\|low" || true
+
+    - name: Publish Scan Results as Artifact
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: docker-scan-results
+        path: ${{ steps.scan.outputs.sarif }}
+
+    - name: Upload Anchore Scan SARIF Report
+      uses: github/codeql-action/upload-sarif@v2
+      with:
+        sarif_file: ${{ steps.scan.outputs.sarif }}
 
   push:
     name: Push to DockerHub
